dist: bionic

language: minimal

env:
  global:
    - REPO=docksal/apache

  matrix:
    - VERSION=2.4 FROM=httpd:2.4.35-alpine TAGS=2.4,latest

install:
  # Install Docksal to have a matching versions of Docker on the build host
  - curl -fsSL https://get.docksal.io | bash
  - fin version
  - fin sysinfo

script:
  - cd ${VERSION}
  - make
  - make test

after_success:
  - ${TRAVIS_BUILD_DIR}/release.sh

after_failure:
  - make logs
