dist: bionic

language: minimal

env:
  global:
    - REPO=docksal/apache
    - LATEST_VERSION=2.4

  matrix:
    - VERSION=2.4 FROM=httpd:2.4.35-alpine

install:
  # Install Docksal to have a matching versions of Docker on the build host
  - curl -fsSL https://get.docksal.io | bash
  - fin version
  - fin sysinfo

script:
  - cd ${TRAVIS_BUILD_DIR}/${VERSION}
  - make
  - make test

after_success:
  - make release

after_failure:
  - make logs
